# rndr = YAML.safe_load_file("render.yaml")
# static_site = rndr["services"].find { _1["env"] == "static" }
# api_site = rndr["services"].find { _1["env"] == "ruby" }
# api_site["name"] => "whitefusion-site-api"
# static_site["routes"] => [{ type, source, destination }]
#

services:
  - type: web
    name: whitefusion-site
    env: static
    buildCommand: bin/bridgetown deploy
    staticPublishPath: ./output
    pullRequestPreviewsEnabled: true
    envVars:
      - key: BRIDGETOWN_ENV
        value: production
      - fromGroup: whitefusion-prod-envs
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-XSS-Protection
        value: "1; mode=block"
      - path: /*
        name: X-Content-Type-Options
        value: "nosniff"
      - path: /*
        name: Strict-Transport-Security
        value: "max-age=15552000; includeSubDomains"
      - path: /*
        name: Referrer-Policy
        value: "no-referrer-when-downgrade"
      - path: /*
        name: Cache-Control
        value: "public, max-age=86400, s-max-age=86400"
    routes:
      - type: rewrite
        source: /contact-form/*
        destination: https://whitefusion-site-api.onrender.com/contact-form/*
      - type: rewrite
        source: /submit-booking/*
        destination: https://whitefusion-site-api.onrender.com/submit-booking/*
      - type: rewrite
        source: /auth/*
        destination: https://whitefusion-site-api.onrender.com/auth/*
      - type: rewrite
        source: /account/*
        destination: https://whitefusion-site-api.onrender.com/account/*
  - type: web
    name: whitefusion-site-api
    env: ruby
    buildCommand: bundle install && yarn install && bin/bridgetown frontend:build
    startCommand: bin/bridgetown start
    envVars:
      - key: BRIDGETOWN_ENV
        value: production
      - fromGroup: whitefusion-prod-envs
